### PR TITLE
added in mini project description

### LINKED ISSUE #63: Add in Winnie's first project description

### PR DESCRIPTION
**Pull request by WCW789**
closes #63

### CODE REVIEW

**Review by thierrychau — CHANGES_REQUESTED** [review]
I think it needs a table header

**Review by thierrychau — APPROVED** [review]

**Review by salcasta — COMMENTED** [review]
looks great!

**Review by salcasta — COMMENTED** [review]
:)

**Review by thierrychau — APPROVED** [review]

**Review by salcasta — COMMENTED** [review]
:)

**Pull request merged**
