### PR TITLE
Added Alonzos First Project

### LINKED ISSUE #201: Add Alonzo's First Project

### PR DESCRIPTION
**Pull request by ricealonzo**
close #201

### CODE REVIEW

**Review by thierrychau — CHANGES_REQUESTED** [review]
I think you are missing the "summary". If you look at the preview, it's offsetting the columns by one cell to the left. Can you update to add this? Thanks

**Comment by ricealonzo** [comment]
Thanks Thierry! The changes have been made.

**Comment by ricealonzo** [comment]
Thank you I made the necessary changes.

**Review by thierrychau — APPROVED** [review]
Looks good!

**Pull request merged**
