### PR TITLE
add my project

### LINKED ISSUE #197: Add Github link for Jennifer's Project

### PR DESCRIPTION
**Pull request by jb520**
closes #197

### CODE REVIEW

**Review by MayaS1111 — APPROVED** [review]
looks good!!

**Comment by thierrychau** [comment]
Great job linking to the issue! The link to render is not working currently. I think you need the `https://...` otherwise it's looking for a relative path. Can you fix this? Woof

**Comment by jb520** [comment]
Updated the link!

**Review by thierrychau — APPROVED** [review]
Woof let's go

**Pull request merged**
