### PR TITLE
added first project

### LINKED ISSUE #232: Adding Alonzo's first project

### PR DESCRIPTION
**Pull request by ricealonzo**
closes #232

### CODE REVIEW

**Review by aldoportillo — DISMISSED** [review]
Create a new section for your cohort and place it under there

**Comment by ricealonzo** [comment]
Hello I have made the corrections to my branch.

**Review by AnnaVi11arrea1 — APPROVED** [review]
looks good!

**Review by teresa-c-pham — APPROVED** [review]
Love your project idea!

**Pull request merged**
